spring.h2.console.enabled : true
spring.jpa.defer-datasource-initialization : true
spring.mvc.pathmatch.matching-strategy : ant-path-matcher
server:
  port: 8011

spring:
  application:
    name: bbl-career #??? ???? ????? ? ???? ?
  profiles:
    active:
      default

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # ??? ???? ?? ??
    fetch-registry: true
    registryFetchIntervalSeconds: 5 # eureka?? ??? ??? ???? ??
    disable-delta: true # eureka?? ??? ??? ???? ??? ??? ????. (false? ?? ??? ????? ??? ????.)
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"