name: Deploy-popool

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-eureka:
    runs-on: ubuntu-latest
    env:
      working-directory: ./bbl-eureka
      module-name: bbl-eureka
      application-name: bbl-eureka
      environment_name: Bbleureka-env
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        working-directory: ${{ env.working-directory }}
        run: chmod +x ./gradlew
        shell: bash

      - name: Build Career with Gradle
        working-directory: ${{ env.working-directory }}
        run: ./gradlew clean build
        shell: bash

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Generate ${{env.module-name}} package
        working-directory: ${{ env.working-directory }}
        run: |
          mkdir -p build-${{env.module-name}}
          cp build/libs/*.jar build-${{env.module-name}}/application.jar
          cp Procfile build-${{env.module-name}}/Procfile
          cp -r .ebextensions build-${{env.module-name}}/.ebextensions
          cd build-${{env.module-name}} && zip -r build-${{env.module-name}}.zip .

      - name: Deploy ${{env.module-name}} to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{env.application-name}}
          environment_name: ${{env.environment_name}}
          version_label: github-action-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: ${{env.module-name}}/build-${{env.module-name}}/build-${{env.module-name}}.zip

  build-career:
    runs-on: ubuntu-latest
    env:
      working-directory: ./bbl-career
      module-name: bbl-career
      application-name: bbl-career
      environment_name: Bblcareer-env-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        working-directory: ${{ env.working-directory }}
        run: chmod +x ./gradlew
        shell: bash

      - name: Build Career with Gradle
        working-directory: ${{ env.working-directory }}
        run: ./gradlew clean build
        shell: bash

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Generate ${{env.module-name}} package
        working-directory: ${{ env.working-directory }}
        run: |
          mkdir -p build-${{env.module-name}}
          cp build/libs/*.jar build-${{env.module-name}}/application.jar
          cp Procfile build-${{env.module-name}}/Procfile
          cp -r .ebextensions build-${{env.module-name}}/.ebextensions
          cd build-${{env.module-name}} && zip -r build-${{env.module-name}}.zip .

      - name: Deploy ${{env.module-name}} to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{env.application-name}}
          environment_name: ${{env.environment_name}}
          version_label: github-action-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: ${{env.module-name}}/build-${{env.module-name}}/build-${{env.module-name}}.zip

  build-common:
    runs-on: ubuntu-latest
    env:
      working-directory: ./bbl-common
      module-name: bbl-common
      application-name: bbl-common
      environment_name: Bblcommon-env
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        working-directory: ${{ env.working-directory }}
        run: chmod +x ./gradlew
        shell: bash

      - name: Build Career with Gradle
        working-directory: ${{ env.working-directory }}
        run: ./gradlew clean build
        shell: bash

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Generate ${{env.module-name}} package
        working-directory: ${{ env.working-directory }}
        run: |
          mkdir -p build-${{env.module-name}}
          cp build/libs/*.jar build-${{env.module-name}}/application.jar
          cp Procfile build-${{env.module-name}}/Procfile
          cp -r .ebextensions build-${{env.module-name}}/.ebextensions
          cd build-${{env.module-name}} && zip -r build-${{env.module-name}}.zip .

      - name: Deploy ${{env.module-name}} to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{env.application-name}}
          environment_name: ${{env.environment_name}}
          version_label: github-action-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: ${{env.module-name}}/build-${{env.module-name}}/build-${{env.module-name}}.zip

  build-member:
    runs-on: ubuntu-latest
    env:
      working-directory: ./bbl-member
      module-name: bbl-member
      application-name: bbl-member
      environment_name: Bblmember-env
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        working-directory: ${{ env.working-directory }}
        run: chmod +x ./gradlew
        shell: bash

      - name: Build Career with Gradle
        working-directory: ${{ env.working-directory }}
        run: ./gradlew clean build
        shell: bash

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Generate ${{env.module-name}} package
        working-directory: ${{ env.working-directory }}
        run: |
          mkdir -p build-${{env.module-name}}
          cp build/libs/*.jar build-${{env.module-name}}/application.jar
          cp Procfile build-${{env.module-name}}/Procfile
          cp -r .ebextensions build-${{env.module-name}}/.ebextensions
          cd build-${{env.module-name}} && zip -r build-${{env.module-name}}.zip .

      - name: Deploy ${{env.module-name}} to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{env.application-name}}
          environment_name: ${{env.environment_name}}
          version_label: github-action-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: ${{env.module-name}}/build-${{env.module-name}}/build-${{env.module-name}}.zip

  build-payment:
    runs-on: ubuntu-latest
    env:
      working-directory: ./bbl-member
      module-name: bbl-member
      application-name: bbl-payment
      environment_name: Bblpayment-env
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        working-directory: ${{ env.working-directory }}
        run: chmod +x ./gradlew
        shell: bash

      - name: Build Career with Gradle
        working-directory: ${{ env.working-directory }}
        run: ./gradlew clean build
        shell: bash

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Generate ${{env.module-name}} package
        working-directory: ${{ env.working-directory }}
        run: |
          mkdir -p build-${{env.module-name}}
          cp build/libs/*.jar build-${{env.module-name}}/application.jar
          cp Procfile build-${{env.module-name}}/Procfile
          cp -r .ebextensions build-${{env.module-name}}/.ebextensions
          cd build-${{env.module-name}} && zip -r build-${{env.module-name}}.zip .

      - name: Deploy ${{env.module-name}} to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{env.application-name}}
          environment_name: ${{env.environment_name}}
          version_label: github-action-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: ${{env.module-name}}/build-${{env.module-name}}/build-${{env.module-name}}.zip
